# Compare with Numpy/SciPy

### We show here some differences between our function and Numpy/SciPy.

###### First, import the libraries necessary for our function operations, we use some constants from the 'math' library and use 'cmath' to provide help for complex number operations.

In [1]:
import math
import cmath

import numpy as np
from scipy.special import gamma, jv

'''
We're also importing Numpy and SciPy here, 
but won't be using them directly, just to compare our outputs.
'''


"\nWe're also importing Numpy and SciPy here, \nbut won't be using them directly, just to compare our outputs.\n"

In [2]:
# Defines an array of numpy arrays for testing and another standard natural number.
x_values = np.array([0.5, 1, 1.5, 10, 15, 20])
y = 5

##### Use recursion to implement our factorial function, which we will use several times.

In [3]:
def factorial(n):
    """Compute factorial of n.
    
    >>> factorial(5)
    120
    >>> factorial(0)
    1

    """
    if n == 0:
        return 1
    return n * factorial(n-1)

##### Comparing our performance in the exp function.

In [4]:
def exp(x, N=100):
    """Compute e^x using Taylor series expansion.
    
    >>> exp(1)
    2.7182818284590455
    >>> exp(0)
    1.0

    """
    x = x if hasattr(x, "__iter__") else [x]
    result = [sum([val**n / factorial(n) for n in range(N)]) for val in x]
    return result if len(result) > 1 else result[0]

print(exp(x_values))
print(np.exp(x_values))
print(exp(y))
print(np.exp(y))

%timeit exp(x_values)
%timeit np.exp(x_values)

[1.6487212707001278, 2.7182818284590455, 4.481689070338066, 22026.46579480671, 3269017.3724721107, 485165195.40979016]
[1.64872127e+00 2.71828183e+00 4.48168907e+00 2.20264658e+04
 3.26901737e+06 4.85165195e+08]
148.41315910257657
148.4131591025766
1.82 ms ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
209 ns ± 1.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Our implementation of the exp function retains more significant digits in the output and is even more accurate than the exp function in the Numpy library, but there is no switch to scientific notation and the output is not user-friendly.

##### Compare our performance in the sin function.

In [5]:
def sin(x, N=10):
    """Compute sin(x) using Taylor series expansion.
       
    >>> sin(0)
    0.0
    >>> sin(math.pi / 2)
    1.0

    """
    # Ensure x is a list
    x = x if hasattr(x, "__iter__") else [x]

    # Reduce each value in x to the range [-pi, pi]
    x_reduced = [(val % (2 * math.pi)) - (2 * math.pi) if val % (2 * math.pi) > math.pi else val % (2 * math.pi) for val in x]
    
    # Calculate the Taylor series expansion for each reduced value
    result = [sum([(-1)**n * val**(2*n+1) / factorial(2*n+1) for n in range(N)]) for val in x_reduced]
    
    return result if len(result) > 1 else result[0]


print(sin(x_values))
print(np.sin(x_values))
print(sin(y))
print(np.sin(y))


%timeit sin(x_values)
%timeit np.sin(x_values)

[0.479425538604203, 0.8414709848078965, 0.9974949866040544, -0.5440211108817542, 0.6502878401546164, 0.9129452507276279]
[ 0.47942554  0.84147098  0.99749499 -0.54402111  0.65028784  0.91294525]
-0.9589242746631386
-0.9589242746631385
38.7 µs ± 227 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
214 ns ± 0.198 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Our implementation of the sin function retains more significant digits in the output and is even more accurate than the sin function in the Numpy library.

##### Compare our performance in the cos function.

In [6]:
def cos(x, N=10):
    """Compute cos(x) using Taylor series expansion.
    
    >>> cos(0)
    1.0

    """
    # Ensure x is a list
    x = x if hasattr(x, "__iter__") else [x]
    
    # Reduce each value in x to the range [-pi, pi]
    x_reduced = [(val % (2 * math.pi)) - (2 * math.pi) if val % (2 * math.pi) > math.pi else val % (2 * math.pi) for val in x]
    
    # Calculate the Taylor series expansion for each reduced value
    result = [sum([(-1)**n * val**(2*n) / factorial(2*n) for n in range(N)]) for val in x_reduced]
    
    return result if len(result) > 1 else result[0]

print(cos(x_values, 30))
print(np.cos(x_values))
print(cos(y))
print(np.cos(y))


%timeit cos(x_values)
%timeit np.cos(x_values)

[0.8775825618903728, 0.5403023058681397, 0.0707372016677029, -0.8390715290764521, -0.7596879128588214, 0.40808206181339135]
[ 0.87758256  0.54030231  0.0707372  -0.83907153 -0.75968791  0.40808206]
0.2836621854632265
0.28366218546322625
35.4 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
218 ns ± 0.276 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Our implementation of the cos function retains more significant digits in the output and is even more accurate than the cos function in the Numpy library.

##### Compare our performance in the tan function.

In [7]:
def tan(x, N=10):
    """Compute tan(x) using Taylor series for sin and cos without calling them directly.
    
    
    >>> tan(0)
    0.0
    >>> tan(math.pi / 4)
    1.0

    """
    
    x = x if hasattr(x, "__iter__") else [x]
    results = []

    for val in x:
        # Reduce the value in x to the range [-pi, pi]
        val_reduced = (val % (2 * math.pi)) - (2 * math.pi) if val % (2 * math.pi) > math.pi else val % (2 * math.pi)

        # Check if reduced value is close to points where tan is undefined
        if math.isclose(val_reduced, math.pi/2, abs_tol=1e-9) or math.isclose(val_reduced, -math.pi/2, abs_tol=1e-9):
            raise ValueError("Tan is not defined for x near (2n+1)*pi/2.")

        # Compute sin(val) using Taylor series expansion
        sin_val = sum([(-1)**n * val_reduced**(2*n+1) / factorial(2*n+1) for n in range(N)])
        
        # Compute cos(val) using Taylor series expansion
        cos_val = sum([(-1)**n * val_reduced**(2*n) / factorial(2*n) for n in range(N)])
        
        if cos_val == 0:
            raise ValueError("Tan is not defined for x where cos(x) = 0.")
        
        results.append(sin_val / cos_val)

    return results if len(results) > 1 else results[0]

print(tan(x_values))
print(np.tan(x_values))
print(tan(y))
print(np.tan(y))


%timeit tan(x_values)
%timeit np.tan(x_values)

[0.5463024898437905, 1.5574077246549025, 14.101419947171992, 0.6483608274019136, -0.8559934008809467, 2.237160944224746]
[ 0.54630249  1.55740772 14.10141995  0.64836083 -0.8559934   2.23716094]
-3.3805150062465827
-3.380515006246585
74.5 µs ± 518 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
223 ns ± 1.34 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Our implementation of the tan function retains more significant digits in the output and is even more accurate than the tan function in the Numpy library.

##### Compare our performance in the gamma function.

In [8]:
def gamma_function(z):
    """Compute the gamma function using the Lanczos approximation.
    
    >>> abs(gamma_function(5) - 24) < 1e-10
    True
    >>> abs(gamma_function(-0.5) - -3.5449077018110335) < 1e-10
    True

    """
    
    # Coefficients for Lanczos approximation
    g = 7
    p = [0.99999999999980993, 676.5203681218851, -1259.1392167224028,
         771.32342877765313, -176.61502916214059, 12.507343278686905,
         -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7]
    
    # If the input is an array-like, recursively apply gamma_function to each element
    try:
        iter(z)  # Checks if z is iterable
        return [gamma_function(zi) for zi in z]
    except TypeError:  # If z is not iterable
        pass

    if z.real < 0.5:
        return cmath.pi / (cmath.sin(cmath.pi * z) * gamma_function(1 - z))
    
    z -= 1
    x = p[0]
    for i in range(1, g+2):
        x += p[i] / (z + i)
    t = z + g + 0.5
    result = cmath.sqrt(2 * cmath.pi) * (t ** (z + 0.5)) * cmath.exp(-t) * x

    # Check if the result is essentially real, and if so, return it as a real number
    if abs(result.imag) < 1e-10:
        return result.real
    return result

print(gamma_function(23.5+4j))
print(gamma(23.5+4j))
print(gamma_function(x_values))
print(gamma(x_values))


%timeit gamma_function(x_values)
%timeit gamma(x_values)

(3.7930039091309634e+21-1.55687559811315e+19j)
(3.7930039091309686e+21-1.5568755981131733e+19j)
[1.7724538509055159, 0.9999999999999998, 0.8862269254527586, 362880.0000000015, 87178291200.00021, 1.2164510040883222e+17]
[1.77245385e+00 1.00000000e+00 8.86226925e-01 3.62880000e+05
 8.71782912e+10 1.21645100e+17]
9.9 µs ± 18.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
225 ns ± 1.21 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


##### Our implementation of the gamma function retains more significant digits in the output and is even more accurate than the gamma function in the SciPy library, but there is no switch to scientific notation and the output is not user-friendly.

##### Compare our performance in Bessel's function.

In [9]:
def bessel_function(alpha, x):
    """Compute the Bessel function of the first kind using the series representation.
    
    >>> abs(bessel_function(0, 1) - 0.7651976865579666) < 1e-10
    True
    >>> abs(bessel_function(1, 1) - 0.44005058574493355) < 1e-10
    True

    """
    # If the input is an array-like, recursively apply bessel_function to each element
    try:
        iter(x)  # Checks if x is iterable
        return [bessel_function(alpha, xi) for xi in x]
    except TypeError:  # If x is not iterable
        pass
    
    sum_term = 0
    m = 0
    epsilon = 1e-15

    while True:
        term = (-1)**m / (factorial(m) * gamma_function(m + alpha + 1)) * (x / 2)**(2 * m + alpha)
        sum_term += term

        # Convergence check
        if abs(term) < epsilon:
            break
        
        m += 1

    return sum_term

print(bessel_function(1, 3+4j))
print(jv(1, 3+4j))
print(bessel_function(1, x_values))
print(jv(1, x_values))

%timeit bessel_function(1, x_values)
%timeit jv(1, x_values)

(3.6541102814142614-8.40310425658308j)
(3.6541102814142636-8.403104256583086j)
[0.24226845767487384, 0.44005058574493344, 0.5579365079100995, 0.04347274616806198, 0.20510403846569988, 0.06683310661421762]
[0.24226846 0.44005059 0.55793651 0.04347275 0.20510404 0.06683312]
229 µs ± 1.87 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.24 µs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


##### Our implementation of the Bessel's function retains more significant digits in the output and is even more accurate than the Bessel's function in the SciPy library.

#### In general, all of these functions that we approximate using Taylor expansions can be made more accurate by increasing the number of bits employed, but this approach also makes our calculations slower.The built-in functions in Numpy or SciPy are usually heavily optimised, with more algorithmic improvements or trade-offs between accuracy and computation time, and with a few overly large or small data are converted to scientific notation to make the output more observable.