In [1]:
import numpy as np
import scipy.linalg as sl
import matplotlib.pyplot as plt

# Question 1 - [25 marks] <a class="tocSkip"></a>

Consider the matrix

$$
\begin{pmatrix}
 1 & -1 &  0 & -1 \\
-1 &  1 &  1 & 1 \\
 1 & -1 &  5 & 0 \\
 3 & -3 &  1 & -1 \\
\end{pmatrix}.
$$

**1.1** Derive the reduced row echelon form (RREF) of this matrix, and determine its rank and nullspace.

In [2]:
A = np.array([[ 1, -1, 0, -1],
  [-1, 1, 1, 1],
  [1, -1, 5, 0],
  [3, -3, 1, -1]])
A0 = A.copy()
A0

array([[ 1, -1,  0, -1],
       [-1,  1,  1,  1],
       [ 1, -1,  5,  0],
       [ 3, -3,  1, -1]])

In [3]:
# create zero entries in first column
# by adding/subtracting scalar multiples of row 0
A0 = np.array([A0[0], A0[1] + A0[0], A0[2] - A0[0], A0[3] - 3*A0[0]])
A0

array([[ 1, -1,  0, -1],
       [ 0,  0,  1,  0],
       [ 0,  0,  5,  1],
       [ 0,  0,  1,  2]])

In [4]:
# create zero entries in third column
# by adding/subtracting scalar multiples of row 1
A0 = np.array([A0[0], A0[1], A0[2] - 5*A0[1], A0[3] - A0[1]])
A0

array([[ 1, -1,  0, -1],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  1],
       [ 0,  0,  0,  2]])

In [5]:
# create zero entries in fourth column
# by adding/subtracting scalar multiples of row 2
A0 = np.array([A0[0]+A0[2], A0[1], A0[2], A0[3] - 2*A0[2]])
A0

array([[ 1, -1,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  0,  1],
       [ 0,  0,  0,  0]])

In [6]:
rank = np.linalg.matrix_rank(A0)
rank

3

In [7]:
nullspace = sl.null_space(A0)
nullspace

array([[0.70710678],
       [0.70710678],
       [0.        ],
       [0.        ]])

This shows that the zero space is tensorized by the vector
$\begin{pmatrix} 1 \\ 1 \\ 0 \\ 0 \end{pmatrix}$

**1.2** Using the solution $x=\left(0, 2, 1, 3\right)$ to the linear system

$$
\begin{pmatrix}
 1 & -1 &  0 & -1 \\
-1 &  1 &  1 & 1 \\
 1 & -1 &  5 & 0 \\
 3 & -3 &  1 & -1 \\
\end{pmatrix}
\begin{pmatrix}
  x_1 \\ x_2 \\ x_3 \\ x_4
\end{pmatrix}
=
\begin{pmatrix}
-5 \\  6 \\  3 \\ -8
\end{pmatrix},
$$

what is the minimum norm solution to this system?

We first need to verify that the given solution $x=(0, 2, 1, 3)$ does indeed satisfy that system. If so, the minimum norm solution will be the solution with the smallest number of norms (usually Euclidean norms) in the solution space of that system.

In [8]:
b = np.array([-5, 6, 3, -8])
x_given = np.array([0, 2, 1, 3])

b_check = A @ (x_given)
solution_matches = np.allclose(b_check, b)
solution_matches

True

The given solution $x=(0, 2, 1, 3)$ does satisfy the linear system. 

In [9]:
A_pinv = np.linalg.pinv(A)
x_min_norm = A_pinv @ (b)
x_min_norm

array([-1.,  1.,  1.,  3.])

This means that while $x=(0, 2, 1, 3)$ is a valid solution to the system, the smallest norm solution is **$x=(-1, 1, 1, 3)$**, which has the smallest Euclidean norm of all possible solutions.

**1.3** Consider now the matrix

$$
\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
  1 & 1 & 1
\end{pmatrix}.
$$

Use [`scipy.linalg.svd`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) to obtain the Singular Value Decomposition of this matrix. Determine the rank of the matrix from the SVD where you may assume any value in the SVD output whose absolute value is smaller than `1e-15` is zero (within machine precision). Again using the output of the SVD, construct the compact form of the SVD and check its product is correct. Use this result to construct a generalised inverse for the matrix, and find the minimum-norm solution of

$$
\begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
  1 & 1 & 1
\end{pmatrix}
\begin{pmatrix}
x_1 \\ x_2 \\ x_3
\end{pmatrix}
=
\begin{pmatrix}
32 \\ 77 \\ 122 \\ 15
\end{pmatrix}
$$


Define the matrix and the vector on the right hand side.

In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 1, 1]
])

b = np.array([32, 77, 122, 15])

Compute Singular Value Decomposition (SVD).

In [11]:
# Compute SVD
U, s, Vh = sl.svd(A)
print(U, s, Vh)

[[-0.2136533   0.87256508 -0.36856761 -0.23904053]
 [-0.51788213  0.2552086   0.47255165  0.66585404]
 [-0.82211097 -0.36214788 -0.10398404 -0.42681351]
 [-0.10140961 -0.20578549 -0.7937507   0.56331896]] [1.69353938e+01 1.09198772e+00 5.97058858e-17] [[-0.48073097 -0.57247058 -0.66421019]
 [-0.77603548 -0.07490508  0.62622533]
 [ 0.40824829 -0.81649658  0.40824829]]


Use the `scipy.linalg.svd` function to compute the singular value decomposition of the matrix `A`, yielding the matrix `U`, the singular value array `s`, and the matrix `Vh` (the conjugate transpose of `V`).

In [12]:
# Determine the rank of the matrix
rank_from_svd = np.sum(s > 1e-15)
rank_from_svd

2

The rank of the matrix is determined by the singular values; any singular value greater than `1e-15` is considered nonzero, and the rank of the matrix is computed.

Constructing an SVD in compact form and checking its product.

In [13]:
# Adjusting the construction of Sigma for a non-square matrix
rows, cols = A.shape
Sigma_expanded = np.zeros((rows, cols))
np.fill_diagonal(Sigma_expanded, s)

# Recompute the reconstructed matrix using the expanded Sigma
A_reconstructed = U @ Sigma_expanded @ Vh

print(A_reconstructed)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 1. 1.]]


Here we construct the compact form of the SVD and then reconstruct the original matrix by the product of `U`, `s` and `Vh` to verify that our SVD is correct. Observing our reconstructed matrix we can see that it is identical to the original matrix, which shows that our implementation is correct.

**Note:** 

When constructing the SVD in compact form and verifying its product, we should note that the original matrix $A$ has the shape $4 \times 3$, not a square matrix. This means that we cannot completely reconstruct the original matrix by directly using simple products of the compact forms of `U`, `s` and `Vh`. For a $4 \times 3$ matrix, `s` should be constructed as a rectangular matrix. The first $rank\_from\_svd$ diagonal elements are singular values and the rest are zero.

In [14]:
# Check its product is correct
correct = np.allclose(A_reconstructed, A)
if correct: print ("Product is correct!")

Product is correct!


In [15]:
# Constructing a generalized inverse
Sigma_pinv_expanded = np.zeros((cols, rows))
np.fill_diagonal(Sigma_pinv_expanded[:rank_from_svd, :], 1/s[:rank_from_svd])
A_pinv_svd = Vh.T @ Sigma_pinv_expanded @ U.T

In [16]:
# Minimum-norm solution
x_min_norm_svd = A_pinv_svd @ (b)
print(x_min_norm_svd)

[4. 5. 6.]


We constructed the generalized inverse and used this generalized inverse to find the minimum norm solution $(4, 5, 6)$ of the linear system.